name: pricebot-daily

on:
  schedule:
    # Запуск каждый день в 06:00 UTC (в октябре это 09:00 по Хельсинки / Europe/Helsinki)
    - cron: "0 6 * * *"
  workflow_dispatch: {}  # кнопка "Run workflow" вручную

permissions:
  contents: write  # нужно, чтобы сохранить last.json обратно в репозиторий

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          URLS: ${{ secrets.URLS }}
        run: python ./bot.py

      - name: Save state (commit last.json)
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name "pricebot"
          git add last.json || true
          git commit -m "state update" || true
          git push || true
